# Splunk Community AI - MCP Server Only
# Lightweight deployment with just the MCP server
# Usage: docker compose -f docker-compose.mcp-only.yml up


services:
  # Catalyst MCP Server - Core service only
  catalyst-mcp:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: catalyst-mcp-server
    ports:
      - "${MCP_PORT:-8443}:8443"
    env_file:
      - .env
    environment:
      # MCP Server Configuration
      - MCP_PORT=8443
      - MCP_TRANSPORT=http
      
      # Splunk Connection - dynamically configured based on auth method
      - SPLUNK_URL=${SPLUNK_URL:-https://host.docker.internal:8089}
      - SPLUNK_AUTH_METHOD=${SPLUNK_AUTH_METHOD:-basic}
      
      # Basic Auth (used when SPLUNK_AUTH_METHOD=basic)
      - SPLUNK_USER=${SPLUNK_USER}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      
      # Token Auth (used when SPLUNK_AUTH_METHOD=token)
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
      
      # Optional: HEC Configuration for audit logging
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_HEC_URL=${SPLUNK_HEC_URL}
      - SPLUNK_HEC_INDEX=${SPLUNK_HEC_INDEX:-catalyst}
      
    volumes:
      - ./knowledge-packs:/app/knowledge-packs:ro
      - ./templates:/app/templates:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Networks for service communication
networks:
  default:
    name: catalyst-network
    external: true