# Standalone MCP Server - No Web Chat Interface
# Use this if you want to integrate the Splunk MCP server with other MCP clients
# or use it programmatically without the LibreChat web interface

services:
  splunk-mcp:
    build: .
    container_name: splunk-mcp-server
    ports:
      - "8443:8443"  # MCP server HTTP endpoint
    environment:
      # Splunk Connection (required)
      - SPLUNK_URL=${SPLUNK_URL:-https://your-splunk-instance:8089}
      - SPLUNK_USER=${SPLUNK_USER}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      
      # Optional: HEC token for log ingestion
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN:-your-hec-token}
      
      # MCP Server Configuration
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8443
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Pack Configuration
      - PACK_NAME=splunk_enterprise
      
    volumes:
      - ./knowledge-packs:/app/knowledge-packs:ro
      - ./logs:/app/logs
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge